sudo ../qemu/build/qemu-system-x86_64 \
        -cpu host \
        -m 8192 \
        -smp 16 \
        -enable-kvm \
        -monitor tcp:0.0.0.0:4444,server,nowait \
        -drive file=vcrypto.qcow2,format=qcow2  \
        -nographic \
        -netdev user,id=mynet0,hostfwd=tcp::2222-:22 -device e1000,netdev=mynet0 \
        -chardev socket,id=chr1,path=/tmp/vhost_crypto.sock \
        -object cryptodev-vhost-user,id=crypto0,chardev=chr1 \
        -device virtio-crypto-pci,cryptodev=crypto0 \
        -object memory-backend-file,id=mem,size=8G,mem-path=/dev/hugepages,share=on \
        -mem-prealloc \
        -numa node,memdev=mem 
